[package]
name = "emu8086"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26.1"
either = "1.8.1"
fstrings = "0.2.3"
trees = "0.4.2"
tui = "0.19.0"
